### PR TITLE
Added links to chats in Telegram

### PR DESCRIPTION
**Pull request by andrey-helldar**

### CODE REVIEW

**Comment by andrey-helldar** [comment]
@Laravel-Lang/laravel-lang, hey!

Thought about it today and decided to create a Telegram chat room for help on projects. I don't know if it will be useful, but I wanted to give it a try.

I created two chat rooms - one for English speakers and one for Russian speakers. If you want, you can create chat rooms for other languages.

I've added links to them in the documentation: https://laravel-lang.com/questions-and-issues.html#fe1kzs_91

Do you think this is a good idea?

**Comment by luisprmat** [comment]
Great idea!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by mohamedsabil83** [comment]
Yep, that will be useful.
We don't need a chat room for Arabic speakers; they'll join the English one, but maybe in the future if we find a need.

**Comment by andrey-helldar** [comment]
@mohamedsabil83. we have a Russian-speaking chat room on Laravel Framework, in which I periodically help people with our project. For this reason, I created a profile chat for help, and I don't know if it's necessary for other languages or not.

If it is needed - we will create it. If not, then no :)

**Comment by andrey-helldar** [comment]
@mohamedsabil83, @ariaieboy, @makowskid, If you don't mind, I will assign admin rights to teammates and display the status as "core" so people can see team members.

If someone doesn't want this, message me and I'll remove it. And I can also give any status I want. Or not at all - in this case Telegram will automatically write "admin".

image

**Comment by mohamedsabil83** [comment]
I agree that **core** will clarify more than **admin** in our situation.

**Comment by andrey-helldar** [comment]
I was guided by the fact that the word "admin" in chat is perceived as "moderator", and "core" clearly makes it clear that the person is a member of a team.

At first I wanted to write "team", but I thought that "core" sounds cooler and more solid :)

**Pull request merged**
